name: CI

on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - "18"
          - "19"
          - "20"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build
        uses: ghacts/static-site@main
        env:
          ASTRO_BASE_URL: "http://localhost:3000/"
        with:
          node-version: ${{ matrix.node-version }}
